### ISSUE TITLE
Download object from a folder

### ISSUE THREAD

**Issue by jstorm31** [vapor-community/google-cloud-kit#29]
I have an issue with downloading an object from a bucket located within a folder. The file path on the bucket is `bucket-id/tickets/test.pdf`. I download it with the following code:
```swift
req.gcs.object.getMedia(bucket: "bucket-id", object: "tickets/test.pdf")
```
I get `CloudStorageAPIError(error: Storage.CloudStorageAPIErrorBody(errors: [], code: 404, message: "Not Found"))` as a response.

Downloading the file directly from the bucket with path `bucket-id/test.pdf` works fine though. The file exists in both paths on the bucket. Creating the file with `req.gcs.object.createSimpleUpload` works fine as well.
```swift
req.gcs.object.getMedia(bucket: "bucket-id", object: "test.pdf")
```

I've checked the library code and it's just an HTTP GET request for the specified path so this is most likely a mistake on my side. But I ran out of ideas where the issue could be. Any ideas? 🤔

**Comment by Andrewangeta** [comment]
What's the url thats being prepared before it gets executed? @jstorm31 Check `StorageObjectAPI.swift` line 397 and print out the constructed string 
`po "\(endpoint)/\(bucket)/o/\(object)"`

**Comment by Andrewangeta** [comment]
Also make sure you're using the latest RC

**Comment by jstorm31** [comment]
@Andrewangeta I have the latest version `1.0.0-rc.3`. The printed URL: `https://www.googleapis.com/storage/v1/b/swapper-storage-bucket/o/tickets/1CFBB8D8-BA19-415D-BF3C-6016BDABBC31.pdf`. Looks good to me. 🤔

**Comment by Andrewangeta** [comment]
Also add a query param `?alt=media` and that should be what's being executed

**Comment by jstorm31** [comment]
I tried to send the request manually from Postman with the URL and I found out the object name including the folder has to be URL encoded as stated [in the documentation](https://cloud.google.com/storage/docs/request-endpoints#encoding). I thought that wasn't necessary since it should be required for writing and copying only. So making a request to this URL works fine from Postman: `https://www.googleapis.com/storage/v1/b/swapper-storage-bucket/o/tickets%2F1CFBB8D8-BA19-415D-BF3C-6016BDABBC31.pdf`.

Then I tried to URL encode the object name including the folder, made a request to the same URL from Vapor and that **failed** again with 404 not found. The server thinks the requested URL is an endpoint when making the request from Vapor for some reason.

**Comment by Andrewangeta** [comment]
@jstorm31 Did you ever end up getting this to work?

**Comment by jstorm31** [comment]
@Andrewangeta  I think I ended up requesting files directly from bucket root and not folder. That worked for me and I didn't further investigate it. 🤷  I guess we can close it?

**Comment by Andrewangeta** [comment]
Sounds good to me.
