### ISSUE TITLE
Change environment variable name

### ISSUE THREAD

**Issue by gustavoggs** [vapor-community/google-cloud-kit#30]
I am using this in a project where we have different services that we connect.

My suggestion is to change the environment variable name from PROJECT_ID to GOOGLE_PROJECT_ID.

What do you think?

**Comment by Andrewangeta** [comment]
@gustavoggs Not sure I'd wanna change this, especially for people already using it. It seems very specific to your problem. Maybe for the different services you use,  `SERVICE_ID` can be used instead? Seems more in line with the terms you're using like `service`.

**Comment by gustavoggs** [comment]
It is not generating any conflict right now, but having only `PROJECT_ID` in the environment variables does not make it clear where this is being used, looks more like a project defined variable than a service defined variable.

**Comment by Andrewangeta** [comment]
Hmmm Not a bad idea. Let's add it in a new breaking release. We have some ideas about other refactoring of the library to make things more generic. I think being very explicit can't hurt. @gustavoggs

**Comment by nathanfallet** [comment]
Could we make something like take `GOOGLE_PROJECT_ID` first, and then if there is nothing check `PROJECT_ID`? So that we don't break anything. I will take a look to this.
