### ISSUE TITLE
No such module 'GoogleCloudKit'

### ISSUE THREAD

**Issue by kamimi01** [vapor-community/google-cloud-kit#50]
Hi, team. I want to use your library with Swift Package Manager.
But `No such module 'GoogleCloudKit'` error has happened when I write as follows.

```swift
import GoogleCloudKit
```

Here is my `Package.swift`.

```swift
// swift-tools-version:5.6
import PackageDescription

let package = Package(
    name: "iOSAppReviewStatusCheckerGCP",
    platforms: [
       .macOS(.v12)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/jwt.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor-community/google-cloud-kit.git", exact: "1.0.0-rc.9")
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "JWT", package: "jwt"),
                .product(name: "GoogleCloudKit", package: "google-cloud-kit"),
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .executableTarget(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)

``` 

Could you tell me how to solve it? Thank you for your cooperation.

**Comment by 0xTim** [comment]
@kamimi01 Which file are you trying to do the import in? And have you tried building it? Sometimes the symbols aren't available until it's been built

**Comment by kamimi01** [comment]
@0xTim Thank you for your reply. 
> Which file are you trying to do the import in?

I want to import "GoogleCloudKit" and use Secret Manager API.

> And have you tried building it?

Yes. I built it. And I tried to do as follows, but I couldn't solve it...(I could import other libraries like "jwt" without no problems)

- Reboot Xcode
- Reboot Macbook
- Clean build folder
- Reset Package Cache
- Resolve Package Versions
- Delete Derived Data

**Comment by 0xTim** [comment]
@kamimi01 right but which specific file? Because if it's `main.swift` it's not going to work for example.

Does `swift build` work?

**Comment by kamimi01** [comment]
@0xTim 
I don't import it in `main.swift` file. I want to import [this](https://github.com/kamimi01/iOSAppReviewStatusCheckerGCP/blob/20feefce7deecf196b94a7c554aa9786ae12bb2f/Sources/App/Usecase/PostAppStateToSlackUseCase.swift#L10) file. [Here](https://github.com/kamimi01/iOSAppReviewStatusCheckerGCP) is my repository.

> Does swift build work?

Unfortunately no. The following error happened.

```
/Users/kamimi/Documents/SourceCode/iOSAppReviewStatusCheckerGCP/Sources/App/Usecase/PostAppStateToSlackUseCase.swift:10:8: error: no such module 'GoogleCloudKit'
import GoogleCloudKit
```

**Comment by 0xTim** [comment]
@kamimi01 ok apologies, this is a quirk/style of SwiftPM. You can add `GoogleCloudKit` as a dependency in your manifest but you have to import the targets that you want. So for instance you can do `import Datastore` or `import SecretManager` (note they're not called `GoogleCloudSecretManager` like the manifest would suggest. You can namespace the targets you want/need in your manifest too.

@Andrewangeta I suggest we look at renaming the targets - `Core` is way too common and will likely cause conflicts.

**Comment by kamimi01** [comment]
@0xTim Thank you so much. I could solve it.
