### ISSUE TITLE
Modularize the lib, just throwing an idea

### ISSUE THREAD

**Issue by portellaa** [vapor-community/google-cloud-kit#6]
Hello all,

Nice work on the first lib structure 👏 🎉 

I'm just throwing an idea, perhaps a silly one, but following the the GoogleCloud libs and Firebase one, what do you say on separate this one into multiple ones?

This one could be the core, which defines some protocols and perhaps the one responsible with make the requests, providing the necessary methods for that, handles the authentication using the Service Account or the specified credentials, token renewal and all of that shared logic.

I'm "starting" doing some work on that, not with specific on this matter and the main focus is to downgrade the kit to use Swift NIO 1 and Vapor related modules to version 3.
That's because i'm using Vapor and Swift in production and since Vapor 4 it's not a good idea upgrade our projects for now.

I don't know what you think of the idea, but for example in my case i have to use `PubSub` from GoogleCloud and so i would not like to bring all the other features from GoogleCloud with me.

I have started some working on this, if you want to follow or provide some feedback, you can check this: https://github.com/YouClap/GoogleCloudKit/pull/1

I will start a new lib, specific to PubSub that has this one as dependency.

Cheers 🍻

**Comment by Andrewangeta** [comment]
@portellaa the vapor 3 compatible version is still on the [google cloud provider](https://github.com/vapor-community/google-cloud-provider/tree/vapor3) vapor3 branch. GoogleCloudKit is meant to be Vapor independent and just use SwiftNIO. If you want to make it compatible with NIO 1.x (which Vapor 3 is using) then you’d have to use URLSession instead of Async-http-client which depends on NIO 2.x in GoogleCloudKit.

**Comment by Andrewangeta** [comment]
As far as Modularizing, I tend to follow the approach of the C# library. All the APIs fall under one dependency which is good for people who need to access multiple APIs for GoogleCloud. The same way installing the gcloud cli gives you access to all the APIs. Same pattern with the [StripeKit](https://github.com/vapor-community/StripeKit) API. You get all of the Stripe APIs rather then Independently depending on Billing, charges, subscriptions etc. it’d be kinda annoying if you had to import many parts of the API
```swift
import StripeBilling
import StripeConnectAccount
import StripePayouts
import StripeProducts
import etc.
```

**Comment by portellaa** [comment]
@Andrewangeta thank you for your answer.

Regarding the version 3, i downgraded and used `HTTPKit` from Vapor (not all Vapor), instead of `URLSession`. I'm using that version i downgraded instead of [google cloud provider](https://github.com/vapor-community/google-cloud-provider/tree/vapor3) vapor3 branch.
In my case, the 3 dependencies i'm using are: 

```
.package(url: "https://github.com/apple/swift-nio.git", from: "1.14.1"),
.package(url: "https://github.com/vapor/http.git", from: "3.2.1"),
.package(url: "https://github.com/vapor/jwt-kit.git", from: "3.0.0")
```

instead of include all Vapor like the [google cloud provider](https://github.com/vapor-community/google-cloud-provider/tree/vapor3) one which is not necessary and besides that include the Storage which i'm not using.


Regarding the modularizing, in the C# you can just include the Pub/Sub  `Install-Package Google.Cloud.PubSub.V1`, or the Storage one `Install-Package Google.Cloud.Storage.V1` and so on, which will resolve all the dependencies you need, as long as for java or other languages officially supported by them.

I think we can't compare `SPM` with `NuGet` (i think that is the official dependency manager for C#) which creates NuGet packages that live in the NuGet gallery instead of reading them directly from GitHub or any other code repository like `SPM`. 
For example if that was a `CocoaPod` the older dependency manager for the mac/iOS world, you could separate this, but regarding SPM this is the "right way" of separate.

Regarding the `import`, well if you need to `import` all the modules in the same file, perhaps you are doing something wrong, but if not, it doesn't seems a problem and you can create a `Kit` that includes all the libs and you just import that, just like Vapor does.

This is just an idea, we can discuss it more, i would love to do it and help growing the lib to support all the GoogleCloud features (my startup it's mostly deployed on Google Cloud, so 😅)
If not, feel free to close this 😊

Cheers 🍻

**Comment by Andrewangeta** [comment]
@portellaa Ah didn't know about how NuGet resolves it's dependencies etc. 
If that's the case, the only thing I'm kind of against is having it broken up into multiple Repos because there's a ton of GCP APIs. 
We can still modularize all the APIs so we can import only the ones we want and that way we don't have to compile all the targets but only the ones we import. And for people who want to use all the APIs with one import we can @_export all the Libraries/Targets under GoogleCloudKit.

Something like this in Package.Swift

```swift
let package = Package(
    name: "GoogleCloudKit",
    products: [
        // GoogleCloudCore can have all the auth stuff etc.
        .library(
            name: "GoogleCloudCore",
            targets: ["GoogleCloudCore"]),
        .library(
            name: "GoogleCloudKit",
            targets: ["GoogleCloudKit"]),
        .library(
            name: "GoogleCloudStorage",
            targets: ["GoogleCloudStorage"]),
        .library(
            name: "GoogleCloudPubSub",
            targets: ["GoogleCloudPubSub"]),
        ],
    dependencies: [
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "GoogleCloudCore",
            dependencies: ["NIO","JWT", "ETC"],
            path: "Sources/GoogleCloudCore"),
        .target(
            name: "GoogleCloudKit",
            dependencies: ["GoogleCloudCore", "GoogleCloudPubSub", "GoogleCloudStorage"],
            path: "Sources/GoogleCloudKit"),
         .target(
            name: "GoogleCloudPubSub",
            dependencies: ["GoogleCloudCore"],
            path: "Sources/GoogleCloudPubSub"),
         .target(
            name: "GoogleCloudStorage",
            dependencies: ["GoogleCloudCore"],
            path: "Sources/GoogleCloudStorage"),
        ]
)
``` 

This would give us a way to keep all the APIs in the same repository rather than having 50+ repositories, but give us the flexibility of importing only what someone may need. Thoughts?

**Comment by portellaa** [comment]
Awesome idea, i didn't remember that and for me sounds like the way to go, instead of manage a lot of repositories, that would be painful.

What if instead of keep all the "sub-libraries" inside of the Sources folder, move them outside and perhaps and then have the `Sources` and `Tests` inside of it.

Awesome idea @Andrewangeta 👏 ⭐️

**Comment by portellaa** [comment]
Hum although, changing the `Sources` and `Tests` position it's not the recommended way for SPM, i think 🤔 and we would have to do more gymnastic in the `target` path. 🤔

**Comment by Andrewangeta** [comment]
@portellaa Nice! And I'm a little confused about your second question

**Comment by portellaa** [comment]
I'll do a small test with my idea, give me a sec please 🙏

**Comment by portellaa** [comment]
Ok, so basically the idea is, module has is own folder in the root folder and inside of that the `Sources` and `Tests` folder.

The package.swift would look like:
```swift
import PackageDescription

let package = Package(
    name: "GoogleCloud",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "GoogleCloudCore",
            targets: ["GoogleCloudCore"]
        ),
        .library(
            name: "GoogleCloudStorage",
            targets: ["GoogleCloudStorage"]
        ),
        .library(
            name: "GoogleCloudPubSub",
            targets: ["GoogleCloudPubSub"]
        ),
        .library(
            name: "GoogleCloudKit",
            targets: ["GoogleCloudCore", "GoogleCloudStorage", "GoogleCloudPubSub"]
        ),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.0.0"),
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.0.0-alpha.1"),
        .package(url: "https://github.com/vapor/jwt-kit.git", from: "4.0.0-alpha")
    ],
    targets: [
        .target(
            name: "GoogleCloudCore",
            dependencies: ["AsyncHTTPClient", "JWTKit", "NIOFoundationCompat"],
            path: "Core/Sources/"
        ),
        .target(
            name: "GoogleCloudStorage",
            dependencies: ["GoogleCloudCore"],
            path: "Storage/Sources/"
        ),
        .target(
            name: "GoogleCloudPubSub",
            dependencies: ["GoogleCloudCore"],
            path: "PubSub/Sources/"
        ),
        .testTarget(
            name: "GoogleCloudCoreTests",
            dependencies: ["GoogleCloudCore", "AsyncHTTPClient"],
            path: "Core/Tests/"
        ),
        .testTarget(
            name: "GoogleCloudStorageTests",
            dependencies: ["GoogleCloudStorage"],
            path: "Storage/Tests/"
        ),
        .testTarget(
            name: "GoogleCloudPubSubTests",
            dependencies: ["GoogleCloudPubSub"],
            path: "PubSub/Tests/"
        ),
    ]
)

```

**notice** instead of Sources/Core and Tests/Core i changed to Core/Sources and Core/Tests, in the filesystem or even git it would be more visible which modules are supported.

It would be something like https://share.getcloudapp.com/bLupk0An or with the files https://share.getcloudapp.com/NQueoK7l

Well, it looks to me a 💄 question 😂 and honestly i don't know which one i prefer 🤔 😅

**Comment by Andrewangeta** [comment]
Nice. And if you don't have an Xcode project file can you still open just the `Package.swift` file in Xcode 11 and it'll compile etc correct?

**Comment by Andrewangeta** [comment]
And yea I think that works well. The first one looks good. And we'd just have to make sure we run the Tests that multiple LinuxMains won't collide etc.

**Comment by portellaa** [comment]
Yeap it works, sorry i forgot to put here the xcodeproj. This is how it look: https://share.getcloudapp.com/jkuyPLod

**Comment by Andrewangeta** [comment]
Cool cool. I'm for this. So basically the API implementations can be shared with the NIO 1.x and NIO 2.x . Just at a networking level we'd have to use a different client etc. Because JWT and Service accounts  will be handled in Core and each API will have it's own implementation of a `Request` for all of it's routes. For example Cloud Storage will have a `CloudStorageRequest` that's used for the AMI routes, the Object routes, the Bucket routes etc. I thought of using a single request type for All API's but realized the APIs differ slightly in ways where trying to force a generic Request type would be annoying. I think the custom Error responses are different per API.

**Comment by portellaa** [comment]
Regarding the network part, i think we can create a layer for the network with a generic request protocol that each module extends and build it's own. The protocol only provides a way to generate an `HTTPRequest` or the object needed by the lib that we decide to use in the core. 
I think in this case is an `HTTPRequest` used by the `async-http-client`, right? 

Ideally this would be agnostic to the modules, they just provide information on which information should be used to generate the `HTTPRequest` and how to encode and decode data. 

What do you think? I can send a proposal with that if you want 😉

**Comment by Andrewangeta** [comment]
Hmmmmm yea lets see what that would look like. Im definitely curious on the Decoding the Errors etc.
https://cloud.google.com/storage/docs/json_api/v1/status-codes
https://cloud.google.com/pubsub/docs/reference/error-codes

**Comment by portellaa** [comment]
Regarding the "new structure", can i submit a PR with those changes?

**Comment by Andrewangeta** [comment]
For the NIO 1.x branch correct?

**Comment by portellaa** [comment]
Oh no, for the filesystem structure, with the modules that we discussed today

**Comment by portellaa** [comment]
https://github.com/YouClap/GoogleCloudKit/tree/feat/restructure if you want to see what i'm talking about

**Comment by portellaa** [comment]
about the NIO 1.x branch, would you like to have that in here? I really need that, i'm using NIO 1.x in production as long as some parts of vapor 3 and i can't just upgrade those services to vapor 4 alpha, it would be a huge risk for the business.

**Comment by Andrewangeta** [comment]
It depends. GCloudKit is supposed to be a break away on Vapor Services and to be used by any SSS framework (Perfect, Kitura etc.) and the provider is supposed to be Vapor specific. There can potentially be a NIO 1.x version but my concern is that since you’re using Vapor 3, (Vapor 4 just dropped it’s Beta a few hours ago btw) you’re relying on vapor 3s HTTP package which also relies on Vapor 3s Core package as well. And it’s starting to look like GCloudKit is relying on a lot of Vapor 3 opinionated implementations for HTTP. Where the provider would seem more appropriate to adopt this new style of folder structure but not live in GCloudKit itself. Because again the idea was to get away from Vapor and use as more Apple specific Swift libraries like AsyncHTTP and NIO of course. Even though I’m using JWTKit, it only uses C OpenSSL libraries under the hood. See where I’m kinda coming from? Also Tagging and versioning with different branches would be confusing potentially.

**Comment by mikkelu** [comment]
I would love the structure as proposed by @portellaa to be implemented. It would make it much easier to create new integrations for different GCP services.

> https://github.com/YouClap/GoogleCloudKit/tree/feat/restructure if you want to see what i'm talking about

**Comment by portellaa** [comment]
> It depends. GCloudKit is supposed to be a break away on Vapor Services and to be used by any SSS framework (Perfect, Kitura etc.) and the provider is supposed to be Vapor specific. There can potentially be a NIO 1.x version but my concern is that since you’re using Vapor 3, (Vapor 4 just dropped it’s Beta a few hours ago btw) you’re relying on vapor 3s HTTP package which also relies on Vapor 3s Core package as well. And it’s starting to look like GCloudKit is relying on a lot of Vapor 3 opinionated implementations for HTTP. Where the provider would seem more appropriate to adopt this new style of folder structure but not live in GCloudKit itself. Because again the idea was to get away from Vapor and use as more Apple specific Swift libraries like AsyncHTTP and NIO of course. Even though I’m using JWTKit, it only uses C OpenSSL libraries under the hood. See where I’m kinda coming from? Also Tagging and versioning with different branches would be confusing potentially.

@Andrewangeta i totally agree with that, i think it shouldn't rely on Vapor libraries. For the Swift NIO 1.x, i think this should be a independent branch that only for people with Vapor 3, not the focus of the library. the master branch and all the releases should be without vapor dependencies and with NIO 2.x

but this is independent of the restructure, the restructure is for the work that is in master. This will keep Swift NIO 2.x and async-http-client has dependencies 😉 

The restructure is this: https://github.com/YouClap/GoogleCloudKit/tree/feat/restructure if you can, take a look, this is just folder re-organization and `Package.swift` with libs separated 🙂

**Comment by Andrewangeta** [comment]
@portellaa yea I’m 100% for the folder restructure.

**Comment by Andrewangeta** [comment]
But that means the google-cloud-provider and googlecloudkit will both have a vapor 3 branch which isn’t the end of the world but again having a Vapor 3 dependent branch of a repository that’s supposed to signal a break away from Vapor seems a little yucky lol

**Comment by portellaa** [comment]
> But that means the google-cloud-provider and googlecloudkit will both have a vapor 3 branch which isn’t the end of the world but again having a Vapor 3 dependent branch of a repository that’s supposed to signal a break away from Vapor seems a little yucky lol

I totally agree with you, the library as it is, with NIO 2.x and using async-http-client, it's perfect in terms of dependencies and i'm not saying to use the Vapor HTTP module, not event close.

What i'm talking about it's just for the branch with NIO 1.x, that i still need because i still have my services running on Vapor 3. As soon as i migrate them, we will not need that anymore. So i can manage and have a fork with that version only for my company.
Although, if you want to have a version or a branch with NIO 1.x, which i think that would be awesome for who is still using Vapor 3 around the world, i can create a version of async-http-client using NIO 1.x.

Let me just clarify this, **I completely agree with you**, 200%, we shouldn't have dependencies to a specific framework, like Vapor, Kitura or whatever, that should be a provider.

Perhaps a nice approach would be to have the client injected by the lib that conforms to a protocol that we define. That way, who's including the lib, would have completely control on which client to use.
That could be something to think, i don't know, it's another idea.

**Comment by portellaa** [comment]
> @portellaa yea I’m 100% for the folder restructure.

Can we ahead with this then? Should i submit a pull request with this new structure?

**Comment by Andrewangeta** [comment]
@portellaa oh yea no worries haha. If you plan on having a branch you forked and manage then that’s totally fine :) and yea go ahead and raise a PR for the restructure. I’ll have a look once I get off work.

**Comment by portellaa** [comment]
@Andrewangeta there it is. I still need to update the README.md. i will do that as soon as possible
